services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src                      
      - ./logs:/app/logs                     
      - .streamlit/:/app/.streamlit           
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: streamlit run src/Homepage.py