name: CI Pipeline

on: 
    pull_request:
        branches:
            - telecom-paris/dev-stable
            - telecom-paris/dev
            - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pydocstyle
        python -m pip install pytest
        
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=src" >> $GITHUB_ENV

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run flake8 for PEP8 compliance
      run: |
        flake8 . --count --select=E,W --max-line-length=79 --max-complexity=10 --statistics --exit-zero


    - name: Run pydocstyle for docstring compliance
      run: |
        pydocstyle .

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Check coverage
      run: |
        coverage report --fail-under=80

  docs:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build documentation
      run: |
        cd docs
        make html
    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/build/html
